import { Project, WorkExperience } from "@/types/portfolio";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "rasovyam-ecommerce",
    title: "Rasovyam - Premium Organic Food & Heritage E-Commerce",
    tagline: "High-conversion D2C e-commerce platform with automated payment & order fulfillment",
    description: "Delivered the comprehensive client online storefront and checkout engine for Rasovyam, an organic food and wellness brand. Developed responsive product catalog filtering, dynamic cart drawers, instant checkout integrations (UPI, Cards, NetBanking), promotional discount engines, and automated order notifications.",
    category: "Personal",
    tags: ["Client Project", "React.js", "Node.js", "WooCommerce / Shopify", "REST APIs", "Payment Gateway", "TailwindCSS"],
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://rasovyam.com",
    githubUrl: "https://github.com/Adarshkumar76/rasovyam-web",
    featured: true,
    createdAt: "2024-05-01",
    stats: {
      commits: "Client Project",
    }
  },
  {
    id: "shopify-woocommerce-ecosystem",
    title: "Shopify & WooCommerce Custom Plugin Suite",
    tagline: "High-performance enterprise e-commerce extensions & webhook automation pipelines",
    description: "Architected and engineered custom Shopify apps and WooCommerce PHP plugins for high-volume client stores. Built automated webhook listeners, real-time inventory synchronization with external ERPs, custom checkout modifiers, and dynamic discount calculators. Optimized database queries and caching to handle flash-sale traffic surges.",
    category: "Company",
    tags: ["Company Project", "Node.js", "PHP", "Shopify API", "WooCommerce", "Liquid", "REST API", "Webhooks", "Redis"],
    image: "https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1200&q=80",
    githubUrl: "https://github.com/adarshku76",
    featured: true,
    createdAt: "2024-03-01",
    stats: {
      commits: "95+ commits",
    }
  },
  {
    id: "sync-craft",
    title: "SyncCraft - Collaborative Workspace Platform",
    tagline: "Real-time synchronized developer collaboration & execution environment",
    description: "Full-stack real-time collaboration suite enabling distributed engineering teams to write, execute, and debug code collaboratively. Features low-latency WebSockets state syncing, room-based audio/chat channels, role-based project workspaces, and automated containerized code sandboxing.",
    category: "Personal",
    tags: ["Next.js", "Node.js", "Express", "WebSockets", "MongoDB", "TailwindCSS", "Docker"],
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/sync-craft",
    githubUrl: "https://github.com/Adarshkumar76/sync-craft",
    featured: true,
    createdAt: "2024-04-15",
  },
  {
    id: "duesora",
    title: "DueSora - Automated Recurring Dues & Billing SaaS",
    tagline: "Enterprise billing automation with invoice generation & smart payment reminders",
    description: "Fintech SaaS platform designed to streamline dues collection, client recurring billing, and receivable tracking. Engineered automated payment reminder triggers, multi-currency PDF invoice generation, Stripe/Razorpay payment gateway integration, and financial analytics dashboard.",
    category: "SaaS",
    tags: ["React", "Node.js", "PostgreSQL", "Prisma", "Stripe API", "TailwindCSS", "JWT Auth"],
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/duesora",
    githubUrl: "https://github.com/Adarshkumar76/duesora",
    featured: true,
    createdAt: "2024-02-10",
  },
  {
    id: "netflix-genai",
    title: "Netflix-GenAI - Semantic Movie Recommendation Engine",
    tagline: "LLM-driven contextual entertainment discovery and conversational search",
    description: "AI-powered entertainment discovery portal combining OpenAI/Gemini LLMs with vector embeddings to deliver conversational, contextual movie recommendations. Users can search by nuanced mood, vague plot descriptions, or character traits rather than basic keyword queries.",
    category: "AI",
    tags: ["React", "Python", "Node.js", "OpenAI API", "Vector Embeddings", "TailwindCSS"],
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/netflix-GENAI",
    githubUrl: "https://github.com/Adarshkumar76/netflix-GENAI",
    featured: true,
    createdAt: "2024-01-20",
  },
  {
    id: "breado",
    title: "Breado - Artisan Food Ordering & Delivery Hub",
    tagline: "End-to-end e-commerce ordering engine with dynamic cart and dispatch tracking",
    description: "Comprehensive e-commerce food ordering application with real-time menu management, dynamic checkout calculations, discount voucher validation, and interactive order status tracking. Built with optimized MongoDB aggregations for swift catalog indexing.",
    category: "Personal",
    tags: ["React.js", "Express.js", "Node.js", "MongoDB", "Redux Toolkit", "Payment Gateway"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/breado",
    githubUrl: "https://github.com/Adarshkumar76/breado",
    featured: false,
    createdAt: "2023-11-12",
  },
  {
    id: "campus-market",
    title: "CampusMarket - Student Peer-to-Peer Trading Platform",
    tagline: "Secure campus marketplace with student verification and direct in-app messaging",
    description: "Decentralized collegiate marketplace built to allow university students to safely buy, sell, and trade textbooks, electronics, and dorm essentials. Features university email domain verification, Cloudinary image hosting with WebP optimization, and instant peer-to-peer WebSocket messaging.",
    category: "Personal",
    tags: ["MERN Stack", "Socket.io", "Cloudinary CDN", "JWT", "TailwindCSS"],
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/campusMarket",
    githubUrl: "https://github.com/Adarshkumar76/campusMarket",
    featured: false,
    createdAt: "2023-10-05",
  },
  {
    id: "smart-agriculture",
    title: "SmartAgriculture - IoT Sensor Telemetry & Analytics",
    tagline: "High-concurrency microservices telemetry engine in Node.js & TypeScript",
    description: "IoT agricultural monitoring solution collecting telemetry data (soil moisture, temperature, ambient light) from hardware sensors. Built backend microservices in Node.js and TypeScript with automated anomaly alerting, graphical time-series metrics, and REST endpoints for mobile field devices.",
    category: "Personal",
    tags: ["TypeScript", "Node.js", "IoT REST API", "Docker", "MongoDB", "Chart.js"],
    image: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/SmartAgriculture",
    githubUrl: "https://github.com/Adarshkumar76/SmartAgriculture",
    featured: false,
    createdAt: "2023-08-18",
  },
  {
    id: "cleaning-service-portal",
    title: "Commercial Facility Service Management Portal",
    tagline: "Client booking CRM with automated quotes, scheduling, and staff dispatch",
    description: "Enterprise service management dashboard for commercial sanitation and facility maintenance operations. Implemented automated quote calculation algorithms based on square footage, recurring appointment calendar booking, staff assignment dispatch, and invoice generation.",
    category: "Company",
    tags: ["React", "Node.js", "Express", "TailwindCSS", "MongoDB", "REST API"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    liveUrl: "https://github.com/Adarshkumar76/cleaning-service",
    githubUrl: "https://github.com/Adarshkumar76/cleaning-service",
    featured: false,
    createdAt: "2023-07-22",
  }
];

export const WORK_EXPERIENCE: WorkExperience[] = [
  {
    id: "exp-1",
    role: "Full Stack Developer (E-Commerce & Custom Plugins)",
    company: "E-Commerce Tech Solutions & Agency",
    period: "2023 - Present",
    location: "Remote / Hybrid (India)",
    type: "Full-time",
    badge: "Current Role",
    description: [
      "Engineered, published, and maintained custom Shopify Apps and WooCommerce Plugins handling tens of thousands of customer checkout sessions daily.",
      "Engineered automated inventory synchronization, webhook ingestion pipelines, and RESTful APIs connecting third-party ERPs and CRMs.",
      "Optimized high-traffic e-commerce storefronts, reducing server latency by 35% and enhancing Core Web Vitals to boost conversion rates.",
      "Implemented secure JWT authentication, webhook HMAC signature validation, and encrypted secret management across distributed services.",
      "Collaborated with cross-functional UI/UX designers and product managers to roll out custom checkout funnels, dynamic cart drawers, and upsell modules."
    ],
    skills: ["Shopify App Bridge", "WooCommerce PHP", "Node.js", "React.js", "TypeScript", "REST APIs", "Webhooks", "PostgreSQL", "Redis", "Docker"]
  },
  {
    id: "exp-2",
    role: "Full Stack Engineer & Web Consultant",
    company: "Freelance & Independent Client Engagements",
    period: "2022 - 2023",
    location: "Global Remote",
    type: "Contract",
    description: [
      "Delivered 12+ end-to-end web applications and SaaS platforms for international clients across e-commerce, fintech, and service industries.",
      "Built responsive MERN (MongoDB, Express, React, Node.js) and Next.js applications featuring interactive dashboards and payment processing.",
      "Standardized deployment workflows using Docker containers, Linux VPS environments, Nginx reverse proxies, and CI/CD pipelines.",
      "Provided architectural consulting on database schema design, indexing, and API performance optimization."
    ],
    skills: ["Next.js", "MERN Stack", "TypeScript", "Docker", "Linux / Nginx", "TailwindCSS", "Stripe", "Git"]
  }
];
