services:
  - type: web
    name: adarsh-portfolio
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_ADMIN_PIN
        value: adarsh2026
      - key: NEXT_PUBLIC_RESUME_URL
        value: /Resume.pdf
